### ISSUE TITLE
Reconstruction Pipeline

### ISSUE THREAD

**Issue by LamboAventador** [lzx551402/geodesc#3]
Hello, thanks for your sharing!

How could I apply GeoDesc to SIFT-based reconstruction pipeline like you did in your paper Fig.5. I'm new in program, any advice would be appreciated.

**Comment by lzx551402** [comment]
To get a quick start, I would suggest you following the instructions of [ETH local feature benchmark](https://github.com/ahojnnes/local-feature-evaluation). You may use the provided script to extract local feature from images, dump them into binary files (<N><D><DESC_1><DESC_2><...><DESC_N>) then run their MATLAB scripts to complete the reconstruction by COLMAP. This is what I did for experiments in Fig.3. I may also provide a script to run the above procedures in the future.

Experiments in Fig.5 were conducted with our own 3D reconstruction pipeline in order to get finer mesh reconstructions. The pipeline is a more efficient with TensorFlow C++ APIs, GPU-based matching and GPU-based keypoint detector.

**Comment by LamboAventador** [comment]
@lzx551402 Thanks for your patient and quick reply. I'll start from your suggestions.

**Comment by riccardogiorato** [comment]
@lzx551402 are you planning on opensourcing your 3D reconstruction pipeline?

**Comment by lzx551402** [comment]
@Giorat I'm afraid not as it is in commercial use (https://www.altizure.com/). But you are welcome to try it out by simply uploading your images to the cloud (free of charge as long as they are not too large).
